# Generated by Django 3.0.6 on 2020-06-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usertweetsmodel',
            name='email',
            field=models.EmailField(default='user@gmail.com', max_length=254),
        ),
    ]
