# Generated by Django 3.0.6 on 2020-06-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_usertweetsmodel_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(null=True, unique=True),
        ),
    ]
