# Generated by Django 3.0.6 on 2020-06-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_usertweetsmodel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertweetsmodel',
            name='url',
            field=models.TextField(),
        ),
    ]
