# Generated by Django 3.0.6 on 2020-06-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0006_auto_20200623_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertweetsmodel',
            name='url',
        ),
        migrations.AddField(
            model_name='usertweetsmodel',
            name='tweet_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='usertweetsmodel',
            name='user_id',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='usertweetsmodel',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='usertweetsmodel',
            name='topic',
            field=models.TextField(default=''),
        ),
    ]
